APPLY_FIXES: none
DISABLE_ERRORS: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: false
LOG_LEVEL: INFO

DISABLE:
  - COPYPASTE
  - SPELL
  - REPOSITORY_GRYPE

DOCKERFILE_HADOLINT_ARGUMENTS: "--failure-threshold error"

YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: "(kustomization\\.yaml)"

BASH_SHFMT_ARGUMENTS: "-i 2 -ci"
