APPLY_FIXES: none
DISABLE_ERRORS: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: false
LOG_LEVEL: INFO

DISABLE:
  - COPYPASTE
  - SPELL
DISABLE_LINTERS:
  - REPOSITORY_GRYPE

DOCKERFILE_HADOLINT_ARGUMENTS: "--failure-threshold error"
BASH_SHFMT_ARGUMENTS: "-i 2 -ci"
